# Configuration for Streamlit Cloud deployment
[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4e73df"
backgroundColor = "#ffffff" 
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[runner]
fastReruns = true
magicEnabled = true

[server]
runOnSave = false
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
#runOnSave = false
#allowRunOnSave = false

[ui]
#hideTopBar = true  # Commented to show top bar